MK_TOP = ../../../..
include $(MK_TOP)/Makefile.master
include $(MK_TOP)/include/Makefile.scidev

MAKETEST_SCRIPT= \
	lev3_specfit.t \
	lev3_f2cratio.t \
	lev3_mho.t \
	lev3_iss.t \
	modelflux.t \
	srcextent.t

include $(MK_TOP)/Makefile.all

#-----------------------------------------------------------------------
# 			MAKEFILE DEPENDENCIES	
#-----------------------------------------------------------------------


announce1:
	@echo "   /---------------------------------------------------------\ "
	@echo "   |              scialg sherpa test scripts                 | "
	@echo "   \---------------------------------------------------------/ "

#
